import LegacyReviews from './LegacyReviews';
import { useCallback, useEffect, useState } from 'react';
import { api } from '../lib/api';
import BookingQuestions from './BookingQuestions';
import './management.css';
import { download, csv } from '../lib/exports';
export function Field({label,value,onChange,type='text',required=false}) {return <label className="block text-sm font-bold">{label}<input className="manage-input" type={type} required={required} value={value??''} onChange={e=>onChange(e.target.value)}/></label>;}
export function Select({label,value,onChange,options}) {return <label className="block text-sm font-bold">{label}<select className="manage-input" value={value??''} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o.value??o} value={o.value??o}>{o.label??o}</option>)}</select></label>;}
export function Action({children,onClick,type='button',disabled=false}) {return <button type={type} onClick={onClick} disabled={disabled} className="manage-button">{children}</button>;}
export function ErrorNotice({error}) {return error?<p role="alert" className="my-3 rounded bg-red-50 p-3 text-red-800">{error}</p>:null;}
const localTime=v=>{if(!v)return '';const d=new Date(v);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
export default function EventWorkspace({events,members,reload}) {
  const [id,setId]=useState(()=>events.find(e=>e.event_date>=new Date().toISOString().slice(0,10))?.id || events.at(-1)?.id || '');
  const [data,setData]=useState(null),[editing,setEditing]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const load=useCallback(async()=>{if(!id)return;try {setData(await api.get(`/api/admin/manage/events/${encodeURIComponent(id)}`));setError('');}catch(e){setError(e.message);}},[id]);
  useEffect(()=>{load();},[load]);
  const changed=async(message)=>{setNotice(message);await load();};
  const questions=JSON.parse(data?.event.booking_fields_json || '{}').questions || [];
  const active=data?.players.filter(p=>p.status==='registered') || [], guests=data?.guests.filter(p=>p.status==='registered') || [];
  const exportRows=()=>[['Name','Type','Status','Buggy','Dietary','Group','Tee time','Handicap',...questions.map(q=>q.label),'Committee notes'],...data.players.map(p=>[p.display_name,'Member',p.status,p.buggy_required?'Yes':'No',p.dietary_requirements || 'Not recorded',p.group_name,p.tee_time,p.handicap,...questions.map(q=>String(JSON.parse(p.preferences_json || '{}')[q.key]??'Not recorded')),p.notes]),...data.guests.map(g=>[g.name,'Guest',g.status,g.buggy_required?'Yes':'No',g.dietary || 'Not recorded',g.group_name,g.tee_time,g.handicap,...questions.map(()=>''),g.notes])];
  return <section className="management space-y-5">
    <div className="no-print flex flex-wrap items-end gap-3"><div className="min-w-64 flex-1"><Select label="Choose event" value={id} onChange={v=>{setData(null);setId(v);}} options={events.map(e=>({value:e.id,label:`${e.event_date} · ${e.title} (${e.status})`}))}/></div><Action onClick={()=>setEditing({status:'draft',booking_fields_json:'{}'})}>New event</Action>{data&&<><Action onClick={()=>setEditing(data.event)}>Edit event</Action><Action onClick={()=>setEditing({...data.event,id:undefined,title:`${data.event.title} — copy`,status:'draft',event_date:'',publication_at:null,registration_opens_at:null,registration_closes_at:null,cancellation_closes_at:null})}>Duplicate</Action></>}</div>
    <ErrorNotice error={error}/>{notice&&<p role="status" className="no-print rounded bg-green-50 p-3 text-green-900">{notice}</p>}
    {editing&&<EventEditor key={editing.id || 'new'} value={editing} close={()=>setEditing(null)} saved={async e=>{setEditing(null);setId(e.id);await reload();await changed('Event saved.');}}/>}
    {data&&<><header><h2 className="text-3xl font-serif font-bold">{data.event.title}</h2><p>{data.event.event_date} · {data.event.venue} · {data.event.tee_time || 'Tee time to be confirmed'}</p></header>
      <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[['Players',active.length+guests.length],['Buggy requests',active.filter(p=>p.buggy_required).length+guests.filter(p=>p.buggy_required).length],['Vegetarian',active.filter(p=>p.dietary_requirements==='Veg').length+guests.filter(p=>p.dietary==='Veg').length],['Cancellations',data.players.length-active.length+data.guests.length-guests.length]].map(([label,n])=><div key={label} className="rounded-xl border bg-white p-4"><strong className="block text-3xl">{n}</strong>{label}</div>)}</div>
      {questions.filter(q=>q.type!=='text').map(q=><p key={q.key} className="rounded bg-white p-3"><strong>{q.label}: </strong>{(q.type==='checkbox'?['Yes','No']:q.options).map(option=>`${option}: ${active.filter(p=>{const a=JSON.parse(p.preferences_json || '{}')[q.key];return q.type==='checkbox'?(option==='Yes'?a===true:a===false):a===option;}).length}`).join(' · ')} · Not recorded: {active.filter(p=>JSON.parse(p.preferences_json || '{}')[q.key]===undefined || JSON.parse(p.preferences_json || '{}')[q.key]==='').length}</p>)}
      <div className="no-print flex flex-wrap gap-3"><Action onClick={()=>download(`${data.event.event_date}-players.csv`,csv(exportRows()))}>Download CSV</Action><Action onClick={()=>window.print()}>Print club list</Action><Action onClick={load}>Refresh list</Action></div>
      <div className="print-only"><p>Prepared {new Date().toLocaleString('en-GB')} · Confirmed players only</p><table><thead><tr>{['Name','Buggy','Dietary','Group','Tee','Handicap',...questions.map(q=>q.label)].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{active.map(p=><tr key={p.id}>{[p.display_name,p.buggy_required?'Yes':'No',p.dietary_requirements || 'Not recorded',p.group_name,p.tee_time,p.handicap,...questions.map(q=>String(JSON.parse(p.preferences_json || '{}')[q.key]??'Not recorded'))].map((v,i)=><td key={i}>{v}</td>)}</tr>)}{guests.map(g=><tr key={g.id}><td>{g.name} (guest)</td><td>{g.buggy_required?'Yes':'No'}</td><td>{g.dietary || 'Not recorded'}</td><td>{g.group_name}</td><td>{g.tee_time}</td><td>{g.handicap}</td>{questions.map(q=><td key={q.key}/>)}</tr>)}</tbody></table></div>
      <div className="no-print space-y-3"><AddPlayer eventId={id} members={members} questions={questions} changed={changed}/><GuestEditor eventId={id} changed={changed}/>
      <LegacyReviews eventId={id} reviews={data.reviews} players={data.players} changed={changed}/><h3 className="text-xl font-bold">Players and preparation</h3><p>Open a name to update requirements, group, tee time or cancellation. Changes save to the website. Buggy totals count requests, not vehicles.</p>
      {data.players.length===0&&<p className="rounded bg-white p-5">No member bookings yet.</p>}{data.players.map(p=><Player key={`${p.id}:${p.version}:${p.preparation_version}`} player={p} questions={questions} changed={changed}/>)}
      {data.guests.map(g=><GuestEditor key={`${g.id}:${g.version}`} guest={g} eventId={id} changed={changed}/>)}
      </div></>}
  </section>;
}
function EventEditor({value,close,saved}) {
  const [form,setForm]=useState(value),[fields,setFields]=useState(JSON.parse(value.booking_fields_json || '{}')),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const update=(k,v)=>setForm({...form,[k]:v});
  const save=async e=>{e.preventDefault();setBusy(true);setError('');try {const result=await api.post(`/api/admin/manage/events${form.id?'/'+encodeURIComponent(form.id):''}`,{...form,bookingFields:fields});await saved(result.event);}catch(e){setError(e.message);}finally{setBusy(false);}};
  const questions=fields.questions || [];
  return <form onSubmit={save} className="no-print space-y-4 rounded-xl border-2 border-jaguar-green bg-white p-5"><h3 className="text-xl font-bold">{form.id?'Edit event':'New event'}</h3><div className="grid gap-4 sm:grid-cols-2">{[['title','Event name','text'],['venue','Venue','text'],['event_date','Event date','date'],['cost','Cost (£)','text'],['meet_time','Meet time','text'],['tee_time','First tee time','text']].map(([k,l,t])=><Field key={k} label={l} type={t} value={form[k]} required={k==='title'||k==='event_date'} onChange={v=>update(k,v)}/>)}<Select label="Status" value={form.status} onChange={v=>update('status',v)} options={['draft','published','open','closed','completed']}/><Field label="Maximum players (blank = no limit)" type="number" value={fields.capacity} onChange={v=>setFields({...fields,capacity:v})}/></div>
    <p className="text-sm">Drafts are private. Published events follow their booking deadlines. Times below use your device’s timezone ({Intl.DateTimeFormat().resolvedOptions().timeZone}).</p><div className="grid gap-4 sm:grid-cols-2">{[['publication_at','Publish at (blank = now)'],['registration_opens_at','Registration opens'],['registration_closes_at','Registration closes'],['cancellation_closes_at','Cancellation closes']].map(([k,l])=><Field key={k} label={l} type="datetime-local" value={localTime(form[k])} onChange={v=>update(k,v?new Date(v).toISOString():null)}/>)}</div>
    {['description','joining_information'].map(k=><label key={k} className="block font-bold">{k==='description'?'Description':'Joining information'}<textarea className="manage-input" rows={3} value={form[k] || ''} onChange={e=>update(k,e.target.value)}/></label>)}
<label className="block"><input type="checkbox" checked={Boolean(fields.isCharity)} onChange={e=>setFields({...fields,isCharity:e.target.checked})}/> Feature on the Charity page</label><Field label="Included package" value={fields.package} onChange={v=>setFields({...fields,package:v})}/><Field label="Day schedule" value={fields.schedule} onChange={v=>setFields({...fields,schedule:v})}/>
    <h4 className="font-bold">Booking questions</h4><p className="text-sm">Buggy and dietary choices are included. Add breakfast, social attendance or other requirements here. New questions do not invent answers for existing players.</p>
    {questions.map((q,i)=><div key={q.key} className="grid gap-3 rounded border p-3 sm:grid-cols-2"><Field label="Question" value={q.label} onChange={v=>setFields({...fields,questions:questions.map((x,j)=>j===i?{...x,label:v}:x)})}/><Select label="Answer type" value={q.type} onChange={v=>setFields({...fields,questions:questions.map((x,j)=>j===i?{...x,type:v,options:v==='select'?['Yes','No','Maybe']:[]}:x)})} options={[{value:'select',label:'Choice'},{value:'text',label:'Short text'},{value:'checkbox',label:'Checkbox'}]}/>{q.type==='select'&&<Field label="Choices (separate with commas)" value={q.options.join(',')} onChange={v=>setFields({...fields,questions:questions.map((x,j)=>j===i?{...x,options:v.split(',')}:x)})}/>}<label><input type="checkbox" checked={q.required} onChange={e=>setFields({...fields,questions:questions.map((x,j)=>j===i?{...x,required:e.target.checked}:x)})}/> Required for new bookings</label><Action onClick={()=>setFields({...fields,questions:questions.filter((_,j)=>j!==i)})}>Remove question</Action></div>)}
    <Action disabled={questions.length>=15} onClick={()=>setFields({...fields,questions:[...questions,{key:'q_'+crypto.randomUUID().replaceAll('-',''),label:'',type:'select',options:['Yes','No','Maybe'],required:false}]})}>Add question</Action><ErrorNotice error={error}/><div className="flex gap-3"><Action type="submit" disabled={busy}>{busy?'Saving…':'Save event'}</Action><Action onClick={close}>Close editor</Action></div></form>;
}
function AddPlayer({eventId,members,questions,changed}) {
  const [memberId,setMemberId]=useState(''),[diet,setDiet]=useState(''),[buggy,setBuggy]=useState(false),[answers,setAnswers]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const save=async e=>{e.preventDefault();setBusy(true);try {await api.post(`/api/admin/manage/events/${encodeURIComponent(eventId)}/bookings`,{memberId,dietaryRequirements:diet,buggyRequired:buggy,preferences:answers});setError('');await changed('Member added.');}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-bold">Add a member booking</summary><form className="mt-4 space-y-3" onSubmit={save}><p className="text-sm">Committee bookings can be added after the deadline. Capacity still applies.</p><Select label="Member" value={memberId} onChange={setMemberId} options={[{value:'',label:'Choose a member'},...members.filter(m=>m.role==='member'&&m.status==='active').map(m=>({value:m.id,label:m.displayName}))]}/><Select label="Dietary choice" value={diet} onChange={setDiet} options={[{value:'',label:'Choose…'},'Veg','Non-veg']}/><label><input type="checkbox" checked={buggy} onChange={e=>setBuggy(e.target.checked)}/> Buggy required</label><BookingQuestions questions={questions} answers={answers} onChange={setAnswers}/><ErrorNotice error={error}/><Action type="submit" disabled={busy||!memberId||!diet}>Add booking</Action></form></details>;
}
function Player({player:p,questions,changed}) {
  const [form,setForm]=useState({...p}),[answers,setAnswers]=useState(JSON.parse(p.preferences_json || '{}')),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const save=async e=>{e.preventDefault();setBusy(true);setError('');try {await api.patch(`/api/admin/bookings/${encodeURIComponent(p.id)}`,{version:p.version,status:form.status,buggyRequired:Boolean(form.buggy_required),dietaryRequirements:form.dietary_requirements,preferences:answers,preparation:{...form,version:p.preparation_version || 0}});await changed(`${p.display_name} saved.`);}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-bold">{p.display_name} <span className="font-normal text-gray-600">· {p.status} · {p.group_name || 'No group'} · {p.buggy_required?'Buggy requested':'No buggy'}</span></summary><form onSubmit={save} className="mt-4 space-y-3"><div className="grid gap-3 sm:grid-cols-2"><Select label="Booking status" value={form.status} onChange={v=>setForm({...form,status:v})} options={['registered','cancelled']}/><Select label="Dietary choice" value={form.dietary_requirements || ''} onChange={v=>setForm({...form,dietary_requirements:v})} options={[{value:'',label:'Not recorded'},'Veg','Non-veg']}/>{[['group_name','Group'],['tee_time','Tee time'],['handicap','Handicap'],['notes','Committee notes']].map(([k,l])=><Field key={k} label={l} value={form[k]} onChange={v=>setForm({...form,[k]:v})}/>)}</div><label><input type="checkbox" checked={Boolean(form.buggy_required)} onChange={e=>setForm({...form,buggy_required:e.target.checked})}/> Buggy required</label><BookingQuestions questions={questions.map(q=>({...q,required:false}))} answers={answers} onChange={setAnswers}/><ErrorNotice error={error}/><Action type="submit" disabled={busy}>Save player</Action></form></details>;
}
function GuestEditor({eventId,guest,changed}) {
  const [form,setForm]=useState(guest || {status:'registered'}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const save=async e=>{e.preventDefault();setBusy(true);try {await api.post(`/api/admin/manage/events/${encodeURIComponent(eventId)}/guests${guest?'/'+encodeURIComponent(guest.id):''}`,form);setError('');await changed('Guest saved.');if(!guest)setForm({status:'registered'});}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-bold">{guest?`${guest.name} · Guest · ${guest.status}`:'Add a guest'}</summary><form onSubmit={save} className="mt-4 space-y-3"><div className="grid gap-3 sm:grid-cols-2">{[['name','Guest name'],['handicap','Handicap'],['social','Social / meal attendance'],['group_name','Group'],['tee_time','Tee time'],['notes','Notes / host name']].map(([k,l])=><Field key={k} label={l} value={form[k]} required={k==='name'} onChange={v=>setForm({...form,[k]:v})}/>)}<Select label="Dietary choice" value={form.dietary || ''} onChange={v=>setForm({...form,dietary:v})} options={[{value:'',label:'Not recorded'},'Veg','Non-veg']}/><Select label="Status" value={form.status} onChange={v=>setForm({...form,status:v})} options={['registered','cancelled']}/></div><label><input type="checkbox" checked={Boolean(form.buggy_required)} onChange={e=>setForm({...form,buggy_required:e.target.checked})}/> Buggy required</label><ErrorNotice error={error}/><Action type="submit" disabled={busy}>{guest?'Save guest':'Add guest'}</Action></form></details>;
}
