import { useState } from 'react';
import { api } from '../lib/api';
import { Action, ErrorNotice, Field } from './EventWorkspace';
export default function LegacyReviews({eventId,reviews=[],players=[],changed}) {
  const [source,setSource]=useState('Historical Google Form'),[csv,setCsv]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const pending=reviews.filter(r=>!r.resolution);
  const upload=async()=>{setBusy(true);try {await api.post(`/api/admin/manage/events/${encodeURIComponent(eventId)}/reviews`,{source,csv});await changed('Historical responses added for review. Website bookings have not been changed.');setCsv('');setError('');}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <details className="rounded-xl border border-amber-300 bg-white p-4"><summary className="cursor-pointer font-bold">Historical registration review · {pending.length} to check</summary><p className="my-3">Compare old form responses against current bookings. Use the player editor or Add a member booking after checking with the member. Then record your resolution here. Repeated imports do not duplicate review entries.</p><details className="my-3"><summary className="cursor-pointer font-bold">Import old responses for review</summary><div className="mt-3 space-y-3"><Field label="Source name" value={source} onChange={setSource}/><label className="block font-bold">Response CSV<textarea aria-label="Response CSV" className="manage-input" rows={4} value={csv} onChange={e=>setCsv(e.target.value)}/></label><label className="block">Or choose a CSV file<input type="file" accept=".csv,text/csv" onChange={async e=>{const f=e.target.files?.[0];if(f){if(f.size>100000){setError('Use a CSV under 100 KB.');return;}setCsv(await f.text());}}}/></label><Action disabled={busy||!csv} onClick={upload}>Import for review</Action><ErrorNotice error={error}/></div></details>{reviews.map(r=><Review key={`${r.id}:${r.resolved_at}`} review={r} players={players} changed={changed}/>)}</details>;
}
function Review({review:r,players,changed}) {
  const [note,setNote]=useState(r.resolution),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const details=JSON.parse(r.details_json);
  const canImport=!r.resolution && !players.some(p=>p.display_name.toLowerCase()===r.name.toLowerCase()) && Object.values(details).includes('Register for event');
  const matches=players.filter(p=>p.display_name.trim().toLowerCase()===r.name.trim().toLowerCase());
  return <details className="my-3 rounded border p-3"><summary className="cursor-pointer font-bold">{r.name} · {r.resolution?'Reviewed':'Needs review'} · {matches.length===1?`Website: ${matches[0].status}`:'No unique website booking'}</summary><dl className="my-3 space-y-2 text-sm">{Object.entries(JSON.parse(r.details_json)).map(([k,v])=><div key={k}><dt className="font-bold">{k}</dt><dd>{v || 'Not answered'}</dd></div>)}</dl>{canImport&&<div className="my-3 rounded bg-amber-50 p-3"><p>Import this explicit registration only when there is no website booking. Recorded buggy, breakfast and social answers are retained. Dietary choice stays unrecorded. Original registration date: {String(details.Timestamp || '').slice(0,10)}.</p><Action disabled={busy} onClick={async()=>{setBusy(true);try {await api.post(`/api/admin/manage/reviews/${r.id}/import-booking`,{registeredOn:String(details.Timestamp || '').slice(0,10)});await changed('Missing registration imported with its original date.');}catch(e){setError(e.message);}finally{setBusy(false);}}}>Import missing booking</Action></div>}<Field label="Resolution / checks made" value={note} onChange={setNote}/><ErrorNotice error={error}/><div className="mt-3"><Action disabled={busy||!note} onClick={async()=>{setBusy(true);try {await api.post(`/api/admin/manage/reviews/${r.id}`,{resolution:note});await changed('Review recorded.');}catch(e){setError(e.message);}finally{setBusy(false);}}}>Record resolution</Action></div></details>;
}
