import { download, csv } from '../lib/exports';
import { useCallback, useEffect, useState } from 'react';
import { api } from '../lib/api';
import { Action, Field, Select, ErrorNotice } from './EventWorkspace';
export default function ManagementRecords({kind}) {
  const [data,setData]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const load=useCallback(async()=>{try {setData(await api.get(`/api/admin/manage/${kind}`));setError('');}catch(e){setError(e.message);}},[kind]);
  useEffect(()=>{load();},[load]);
  const saved=async()=>{setNotice('Saved to the website.');await load();};
  return <section className="space-y-4"><ErrorNotice error={error}/>{notice&&<p role="status" className="rounded bg-green-50 p-3">{notice}</p>}{data&&(kind==='balances'?<><h2 className="text-3xl font-serif font-bold">Member balances</h2><p>Record the reconciled balance and date after checking payments and event charges. Positive means credit; negative means money owed. Bookings after that date are deducted in the member’s forecast. This does not collect payments.</p><Action onClick={()=>download('member-balances.csv',csv([['Member','Balance GBP','Reconciled on','Note'],...data.balances.map(b=>[b.display_name,b.balance_pence==null?'':b.balance_pence/100,b.reconciled_on,b.note])]))}>Download balances</Action>{data.balances.map(b=><BalanceRow key={`${b.id}:${b.version}`} value={b} saved={saved}/>)}</>:kind==='results'?<ResultsEditor key={data.generation} data={data} saved={saved}/>:<><h2 className="text-3xl font-serif font-bold">Recent changes</h2>{data.history.map(h=><details key={h.id} className="rounded border bg-white p-4"><summary>{new Date(h.created_at).toLocaleString('en-GB')} · {h.actor} · {h.entity_type} {h.action}</summary><pre className="overflow-auto whitespace-pre-wrap text-sm">{JSON.stringify(JSON.parse(h.after_json),null,2)}</pre></details>)}</>)}</section>;
}
function BalanceRow({value:b,saved}) {
  const [amount,setAmount]=useState(b.balance_pence==null?'':String(b.balance_pence/100)),[date,setDate]=useState(b.reconciled_on || ''),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const save=async e=>{e.preventDefault();setBusy(true);try {await api.post(`/api/admin/manage/balances/${encodeURIComponent(b.id)}`,{amount,reconciled_on:date,note,version:b.version || 0});await saved();}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-bold">{b.display_name} · {b.balance_pence==null?'Balance not recorded':new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(b.balance_pence/100)} · {b.reconciled_on || 'Needs review'}</summary><form onSubmit={save} className="mt-4 space-y-3"><div className="grid gap-3 sm:grid-cols-3"><Field label="Reconciled balance (£)" value={amount} onChange={setAmount} required/><Field label="Reconciled through" type="date" value={date} onChange={setDate} required/><Field label="Reason / payment reference" value={note} onChange={setNote} required/></div><p className="text-sm">Previous note: {b.note || 'None'}</p><ErrorNotice error={error}/><Action type="submit" disabled={busy}>Save balance</Action></form></details>;
}
function ResultsEditor({data,saved}) {
  const [entries,setEntries]=useState(data.entries),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const update=(i,k,v)=>setEntries(entries.map((e,j)=>j===i?{...e,[k]:v}:e));
  const save=async e=>{e.preventDefault();setBusy(true);try {await api.post('/api/admin/manage/results',{generation:data.generation,entries});await saved();}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <form onSubmit={save} className="space-y-4"><h2 className="text-3xl font-serif font-bold">Competition results</h2><p>Save publishes these results to the website’s leaderboard. Existing history is kept until you change it.</p><Action onClick={()=>setEntries([{category:'poy',year:new Date().getFullYear(),winner:'',score:''},...entries])}>Add result</Action><div className="space-y-3">{entries.map((e,i)=><div key={i} className="grid gap-3 rounded border bg-white p-4 sm:grid-cols-5"><Select label="Competition" value={e.category} onChange={v=>update(i,'category',v)} options={[{value:'poy',label:'Player of the year'},{value:'singles',label:'Singles'},{value:'radha',label:'Radha'},{value:'doubles',label:'Doubles'}]}/><Field label="Year" value={e.year} type="number" onChange={v=>update(i,'year',v)}/><Field label="Winner" value={e.winner} onChange={v=>update(i,'winner',v)} required/><Field label="Score" value={e.score} onChange={v=>update(i,'score',v)}/><Action onClick={()=>setEntries(entries.filter((_,j)=>j!==i))}>Remove</Action></div>)}</div><ErrorNotice error={error}/><Action type="submit" disabled={busy}>Save and publish results</Action></form>;
}
export function ManagementHelp() {
  const [error,setError]=useState('');
  return <section className="space-y-5 rounded-xl border bg-white p-6"><h2 className="text-3xl font-serif font-bold">Running an event</h2><ol className="list-decimal space-y-3 pl-6"><li>In Events, duplicate a previous event or choose New event. Set the venue, date, cost and booking deadlines.</li><li>Add booking questions such as breakfast or social attendance. Save as a draft until ready, then publish.</li><li>Members register on the website. Their bookings immediately appear in the event workspace.</li><li>Before the game, check missing answers, add guests, assign groups and tee times, then print the club list or download CSV. Cancelled players stay visible for reference.</li><li>Record reconciled member balances in Balances. Publish competition winners in Results. Mark the event completed when finished.</li></ol><p>Use Members to add accounts, update contact details or reset access. Routine changes do not need a deployment.</p><p>Old Google Forms and Sheets are historical references after the switch. Do not use them for new registrations. CSV exports are optional copies; editing an export does not change website records.</p><p>Before moving any old form entry, compare it with the website booking. Check conflicts with the member, especially cancellations. Do not infer a dietary choice from an unanswered question.</p><h3 className="text-xl font-bold">Keep a copy</h3><p>Download a protected records backup periodically. It includes member contact details, bookings, preparation, balances and results. Keep it with committee records. Hosting recovery remains a technical task.</p><Action onClick={async()=>{try {download('jgs-records-backup.json',JSON.stringify(await api.get('/api/admin/manage/backup'),null,2),'application/json');}catch(e){setError(e.message);}}}>Download records backup</Action><ErrorNotice error={error}/></section>;
}
