import {useCallback,useEffect,useState} from 'react';
import {api} from '../lib/api';
import {Action,Field,ErrorNotice} from './EventWorkspace';
const money=v=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(v/100);
export default function MemberBalanceCard(){
  const [balance,setBalance]=useState(null),[ledger,setLedger]=useState(null),[error,setError]=useState('');
  const load=useCallback(async()=>{
    const result=await api.get('/api/account/statement');setLedger(result);
    if(!result.active)setBalance(await api.get('/api/account/balance'));
  },[]);
  useEffect(()=>{load().catch(e=>setError(e.message));},[load]);
  if(ledger?.active)return <section className="space-y-4 rounded-xl border bg-white p-5"><h2 className="text-2xl font-bold">Your private account</h2><div className="grid gap-3 sm:grid-cols-3"><p>Amount due now<br/><strong className="text-2xl">{money(ledger.dueNowPence)}</strong></p><p>Upcoming charges<br/><strong className="text-2xl">{money(ledger.upcomingPence)}</strong></p><p>Available credit<br/><strong className="text-2xl">{money(ledger.availableCreditPence)}</strong></p></div><p>Bank data through {ledger.bankDataThrough}. Transfers made later may not appear yet. {ledger.unresolvedBankItems?'Some bank payments are still being checked.':''}</p><p>Confirmed credit covers recorded charges in due-date order. {ledger.bookingChargesEnabled?'New live bookings after your opening cutoff automatically record the event fee, due on the configured payment date or the event date. Free events have no charge.':'Automatic booking charges need setup. Ask Chetan to check that your event charges have been recorded.'} A booking confirmation is not payment confirmation. Historical bookings are not backfilled; ask Chetan about missing charges.</p>
    {(ledger.bookingReviews || []).length>0&&<div className="rounded border border-amber-200 bg-amber-50 p-4"><h3 className="font-bold">Cancellation charge reviews</h3><p>A cancellation review does not clear your charge. It remains on your account unless released. Releasing a charge does not send a cash refund.</p>{ledger.bookingReviews.map((review,i)=><p className="my-2" key={`${review.created_at}:${review.event_title}:${i}`}>{review.event_title} · {review.created_at} · {review.status==='pending'?'Awaiting review — charge retained':review.resolution==='release'?'Resolved — charge released':review.resolution==='retain'?'Resolved — charge retained':'Resolved'}</p>)}</div>}
    <details><summary className="cursor-pointer font-bold">Charges and payment history</summary>{ledger.charges.map(c=><p className="my-2" key={c.id}>{c.eventCode} {c.category} {c.note} · Due {c.dueOn} · Remaining {money(c.outstandingPence)}</p>)}<hr/>{ledger.entries.map(e=><p className="my-2" key={e.id}>{e.posted_on} · {e.kind} · {money(e.amount_pence)} · {e.event_code} {e.category} · {e.note}{ledger.entries.some(r=>r.reverses_id===e.id)?' (reversed)':''}</p>)}</details>
    <details><summary className="cursor-pointer font-bold">I've paid — ask Chetan to check</summary><PaymentClaim load={load}/></details>{ledger.claims.map(c=><p key={c.id}>{money(c.amount_pence)} reported paid on {c.paid_on}: {c.status==='pending'?'Awaiting verification — your confirmed balance has not changed':c.resolution}</p>)}<ErrorNotice error={error}/></section>;
  return <section className="rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">Your private balance</h2>{balance?<><p className="my-3 text-3xl font-bold">{money(balance.projectedBalancePence)}</p><p>After bookings made since the {balance.reconciledOn} reconciliation. Positive is credit; negative is the amount to pay.</p></>:<p className="mt-3">{error || 'Loading your balance…'}</p>}</section>;
}
function PaymentClaim({load}){
  const [amount,setAmount]=useState(''),[paidOn,setDate]=useState(''),[reference,setReference]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[requestId,setRequestId]=useState(()=>crypto.randomUUID());
  return <form className="my-3 space-y-3" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api.post('/api/account/statement/claims',{amount,paidOn,reference,requestId});await load();setAmount('');setReference('');setRequestId(crypto.randomUUID());setError('');}catch(e){setError(e.message);}finally{setBusy(false);}}}><p>This records a payment for review. It does not make a transfer or mark your account paid.</p><Field label="Amount (£)" value={amount} onChange={setAmount} required/><Field label="Date paid" type="date" value={paidOn} onChange={setDate} required/><Field label="Reference used" value={reference} onChange={setReference} required/><ErrorNotice error={error}/><Action type="submit" disabled={busy}>Submit for review</Action></form>;
}
