import {useCallback,useEffect,useState} from 'react';
import {api} from '../lib/api';
import {readBankFile} from '../lib/bank-file';
import {Action,Field,Select,ErrorNotice} from './EventWorkspace';
import {csv,download} from '../lib/exports';

const money=v=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(v/100);
const options=members=>[{value:'',label:'Choose member'},...members.map(m=>({value:m.id,label:m.display_name}))];
export default function Reconciliation({events=[]}) {
  const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[selected,setSelected]=useState({});
  const load=useCallback(async()=>{setData(await api.get('/api/admin/reconciliation'));setSelected({});},[]);
  useEffect(()=>{load().catch(e=>setError(e.message));},[load]);
  const save=async(path,input)=>{setBusy(true);setError('');try{const result=await api.post(`/api/admin/reconciliation/${path}`,{...input,revision:data.revision});await load();setNotice('Saved. Member statements reflect confirmed entries.');return result;}catch(e){setError(e.message);throw e;}finally{setBusy(false);}};
  const attempt=fn=>fn().catch(()=>{});
  if(!data)return <p>{error || 'Loading reconciliation…'}</p>;
  if(!data.available)return <section className="space-y-4 rounded-xl border bg-white p-5"><h2 className="text-2xl font-bold">Enable reconciliation</h2><p>Prepare the reconciliation workspace. Existing member balances remain in place until each opening account is checked and approved. This does not import payments or activate accounts.</p><ErrorNotice error={error}/><Action disabled={busy} onClick={()=>attempt(()=>save('setup',{}))}>Enable reconciliation</Action></section>;
  const active=data.accounts.filter(a=>a.active);
  return <section className="space-y-6"><h2 className="text-3xl font-serif font-bold">Reconciliation</h2><p>Upload your original bank CSV or Excel export. Read the memo, assign members and add event/category detail. Only confirmed entries change accounts.</p><ErrorNotice error={error}/>{notice&&<p role="status">{notice}</p>}
    <ImportForm revision={data.revision} save={save} busy={busy}/>
    {!data.bookingChargesEnabled&&<Action disabled={busy} onClick={()=>attempt(()=>save('setup',{}))}>Enable automatic booking charges</Action>}
    {(data.openingBookings || []).length>0&&<details className="rounded-xl border bg-white p-4"><summary>Check bookings that existed before account activation ({data.openingBookings.length})</summary><p>Before rebooking, confirm whether the previous booking is already covered by the opening balance. This check does not change the balance. For cancelled historical bookings, separately record any agreed credit adjustment.</p>{data.openingBookings.map(b=><OpeningBooking key={b.booking_id} booking={b} save={save} busy={busy}/>)}</details>}
    <details className="rounded-xl border bg-white p-4"><summary>Bank movement control totals</summary><p>Totals across imported rows. Duplicate rows are shown separately and must be excluded from bank movement totals. These are transaction controls, not proof of the bank's closing balance.</p>{data.controlTotals.map(t=><p key={t.status}>{t.status}: {t.count} rows · In {money(t.in_pence)} · Out {money(t.out_pence)}</p>)}</details>
    {!data.bookingChargesEnabled&&<p role="status">Automatic booking charges need setup. Apply the booking-charge database update before relying on automatic charges or cancellation reviews. Continue recording missing charges manually after checking opening balances.</p>}
    {data.bookingChargesEnabled&&<div className="rounded-xl border bg-white p-4"><h3 className="text-xl font-bold">Cancellation charges to review ({(data.bookingReviews || []).length})</h3><p>Cancellation keeps the charge until reviewed, unless the event releases it before the cancellation deadline. Retain confirms the charge; release reverses it. Neither action sends a cash refund.</p>{!(data.bookingReviews || []).length&&<p className="mt-3">No cancellation charges awaiting review.</p>}{(data.bookingReviews || []).map(review=><BookingReview key={review.id} review={review} save={save} busy={busy}/>)}</div>}
    <EventCharges events={events} revision={data.revision} save={save} busy={busy}/>
    <div className="rounded-xl border bg-white p-4"><h3 className="text-xl font-bold">Payments to review ({data.pending.length})</h3><p>Full-name matches are suggestions only. The bank Number column is not unique. Similar transactions need individual review.</p>
      <Action disabled={busy || !Object.keys(selected).length || Object.keys(selected).length>20} onClick={()=>attempt(()=>save('batch',{rows:Object.entries(selected).map(([id,memberId])=>{const row=data.pending.find(r=>r.id===id);return {id,status:'posted',note:'Reviewed memo and confirmed member',splits:[{memberId,amount:String(row.amount_pence/100),description:'Bank payment received',category:'',eventCode:''}]};})}))}>Confirm {Object.keys(selected).length} selected receipts</Action>
      {data.pending.map(row=><details key={`${row.id}:${data.revision}`} className="my-3 rounded border p-4"><summary className="cursor-pointer"><strong>{row.posted_on} · {money(row.amount_pence)}</strong> · {row.memo}{row.possibleDuplicate?' · Possible duplicate':''}</summary>
        {row.amount_pence>0&&!row.possibleDuplicate&&<div className="my-3"><Select label="Quick assignment (select up to 20, then confirm above)" value={selected[row.id] || ''} options={options(active)} onChange={value=>setSelected(old=>{const next={...old};if(value)next[row.id]=value;else delete next[row.id];return next;})}/>{row.suggestedMemberId&&<p>Suggested: {data.members.find(m=>m.id===row.suggestedMemberId)?.display_name} — check the memo before choosing.</p>}</div>}
        <RowForm row={row} members={active} busy={busy} save={save}/></details>)}
    </div>
    <details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-bold">Correct a reviewed bank transaction (latest 100)</summary><p>Corrections reverse prior member entries and record the replacement treatment together. The original bank evidence stays intact.</p>{data.resolved.map(row=><details key={`${row.id}:${data.revision}`} className="my-3 border p-3"><summary>{row.posted_on} · {money(row.amount_pence)} · {row.memo} · {row.status}</summary><p>Previous review: {row.resolution}</p><RowForm row={row} members={active} save={save} busy={busy}/></details>)}</details>
    <div className="rounded-xl border bg-white p-4"><h3 className="text-xl font-bold">Member accounts</h3><p>Approve an opening balance and cutoff before posting. Positive means credit; negative means debt. Include all charges already reflected in that opening figure. Thereafter record charges and corrections, not replacement balances.</p>
      <Action onClick={()=>download('jgs-accounts.csv',csv([['Member','Due now GBP','Upcoming GBP','Credit GBP','Bank data through'],...active.map(a=>[a.display_name,a.dueNowPence/100,a.upcomingPence/100,a.availableCreditPence/100,a.bankDataThrough])]))}>Download who owes what</Action>
      {data.accounts.map(a=><details key={`${a.id}:${data.revision}`} className="my-3 rounded border p-4"><summary className="cursor-pointer font-bold">{a.display_name} · {a.active?`Due now ${money(a.dueNowPence)} / Upcoming ${money(a.upcomingPence)} / Credit ${money(a.availableCreditPence)}`:'Opening balance needs approval'}</summary>{a.active?<><p className="my-3">Bank data through {a.bankDataThrough}. {a.unresolvedBankItems?'Some bank items remain unresolved.':''} {data.bookingChargesEnabled?'New live registrations after the opening cutoff automatically record the event fee for activated accounts. Historical bookings are not backfilled. Free events have no charge; changes to booking preferences at the same price do not charge again.':'Automatic booking charges need setup. Record missing charges manually after checking opening balances.'}</p><EntryForm account={a} save={save} busy={busy}/>{a.entries.map(e=><div key={e.id} className="my-3 border-t pt-2"><p>{e.posted_on} · {e.kind} · {money(e.amount_pence)} · {e.event_code} · {e.category} · {e.note}</p>{!['opening','reversal'].includes(e.kind)&&!a.entries.some(r=>r.reverses_id===e.id)&&<ReverseForm id={e.id} save={save} busy={busy}/>}</div>)}</>:<OpeningForm memberId={a.id} save={save} busy={busy}/>}</details>)}
    </div>
    <div className="rounded-xl border bg-white p-4"><h3 className="text-xl font-bold">Member payment claims</h3><p>A claim does not clear a balance. Check bank evidence before resolving it.</p>{data.claims.map(c=><div key={c.id} className="my-3 border-t p-3"><p>{c.display_name} · {c.paid_on} · {money(c.amount_pence)} · {c.reference}</p><ReverseForm id={c.id} save={save} busy={busy} claim/></div>)}</div>
    <details><summary>Import history and backup</summary>{data.imports.map(i=><p key={i.id}>{i.filename} · declared coverage {i.coverage_from} to {i.coverage_through} · imported {i.created_at}</p>)}<Action onClick={()=>api.get('/api/admin/reconciliation/backup').then(b=>download('jgs-reconciliation-backup.json',JSON.stringify(b,null,2),'application/json')).catch(e=>setError(e.message))}>Download protected finance backup</Action><p>Contains private bank evidence. Keep with restricted committee records.</p></details>
  </section>;
}
function OpeningBooking({booking,save,busy}) {
  const [note,setNote]=useState(''),[disposition,setDisposition]=useState('');
  return <form className="my-3 space-y-3 border p-3" onSubmit={e=>{e.preventDefault();save('opening-booking',{id:booking.booking_id,disposition,note}).catch(()=>{});}}><p>{booking.member_name} · {booking.event_title} · {booking.status}</p><Select label="Treatment of a future rebooking" value={disposition} onChange={setDisposition} options={[{value:'',label:'Choose after checking the opening evidence'},{value:'included',label:'Already covered — do not charge again'},{value:'excluded',label:'Not covered — charge if booked again'}]}/><Field label="Opening evidence and reason" value={note} onChange={setNote} required/><Action type="submit" disabled={busy||!disposition||!note.trim()}>Confirm historical treatment</Action></form>;
}
function BookingReview({review,save,busy}) {
  const [note,setNote]=useState(''),[resolution,setResolution]=useState('retain');
  return <form className="my-3 space-y-3 rounded border p-4" onSubmit={e=>{e.preventDefault();save('booking-review',{id:review.id,resolution,note}).catch(()=>{});}}>
    <p><strong>{review.member_name} · {review.event_title}</strong> · {money(review.amount_pence)} · Cancelled {review.created_at}</p>
    <Select label="What should happen to this charge?" value={resolution} onChange={setResolution} options={[{value:'retain',label:'Retain charge — member still owes it'},{value:'release',label:'Release charge — reverse it on the account'}]}/>
    <Field label="Reason for this decision (committee only)" value={note} onChange={setNote} required/>
    <Action type="submit" disabled={busy||!note.trim()}>{resolution==='release'?'Confirm release of charge':'Confirm retained charge'}</Action>
  </form>;
}
function EventCharges({events,revision,save,busy}) {
  const [eventId,setEvent]=useState(''),[amount,setAmount]=useState(''),[postedOn,setDate]=useState(''),[dueOn,setDue]=useState(''),[result,setResult]=useState(null),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false),[bookingIds,setIds]=useState([]);
  const change=setter=>v=>{setter(v);setResult(null);setConfirmed(false);};
  return <form className="space-y-3 rounded-xl border bg-white p-4" onSubmit={async e=>{e.preventDefault();try{const p=await api.post('/api/admin/reconciliation/event-preview',{eventId,amount,postedOn,dueOn});setResult(p);setIds(p.bookings.filter(b=>b.eligible).slice(0,30).map(b=>b.id));setError('');}catch(e){setError(e.message);}}}><h3 className="text-xl font-bold">Historical event charge catch-up</h3><p>Use only for historical bookings missing a charge. Preview registered members, check the fee and confirm up to 30 at a time. Bookings already charged automatically or manually are excluded by the preview and posting checks. Guests and different tariffs can be charged individually under Member accounts.</p><Select label="Event" value={eventId} onChange={v=>{change(setEvent)(v);setAmount(String(events.find(e=>e.id===v)?.cost ?? ''));}} options={[{value:'',label:'Choose event'},...events.map(e=>({value:e.id,label:e.title}))]}/><div className="grid gap-3 sm:grid-cols-3"><Field label="Fee per member (£)" value={amount} onChange={change(setAmount)} required/><Field label="Posting date" type="date" value={postedOn} onChange={change(setDate)} required/><Field label="Payment due" type="date" value={dueOn} onChange={change(setDue)} required/></div><Action type="submit" disabled={busy}>Preview charges</Action><ErrorNotice error={error}/>{result&&<><div className="max-h-64 overflow-auto">{result.bookings.map(b=><label key={b.id} className="block p-2"><input type="checkbox" disabled={!b.eligible} checked={bookingIds.includes(b.id)} onChange={e=>setIds(old=>e.target.checked?[...old,b.id]:old.filter(id=>id!==b.id))}/> {b.display_name} · {b.reason || money(result.value)}</label>)}</div><label className="block"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> These historical charges are due, are not already charged and are not included in opening balances.</label><Action disabled={busy||!confirmed||!bookingIds.length||bookingIds.length>30||revision!==result.revision} onClick={async()=>{try{await save('event-charges',{eventId,amount,postedOn,dueOn,bookingIds,confirmed});setResult(null);}catch{/* error in parent */}}}>Confirm {bookingIds.length} event charges</Action></>}</form>;
}
function ImportForm({revision,save,busy}) {
  const [source,setSource]=useState(null),[filename,setFilename]=useState(''),[from,setFrom]=useState(''),[through,setThrough]=useState(''),[result,setResult]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  const inspect=async e=>{e.preventDefault();setLoading(true);setError('');try{setResult(await api.post('/api/admin/reconciliation/preview',{...source,coverageFrom:from,coverageThrough:through}));}catch(e){setError(e.message);}finally{setLoading(false);}};
  return <form onSubmit={inspect} className="space-y-3 rounded-xl border bg-white p-4"><h3 className="text-xl font-bold">Import bank file</h3><label className="block">Original bank CSV / XLSX<input type="file" accept=".csv,.xlsx" className="block w-full" onChange={async e=>{setResult(null);setSource(null);const file=e.target.files[0];if(!file)return;try{setSource(await readBankFile(file));setFilename(file.name);setError('');}catch(e){setError(e.message);}}}/></label><div className="grid gap-3 sm:grid-cols-2"><Field label="Export period starts" type="date" value={from} onChange={v=>{setFrom(v);setResult(null);}} required/><Field label="Export period ends" type="date" value={through} onChange={v=>{setThrough(v);setResult(null);}} required/></div><p>Use the period requested from the bank, including days with no transactions. These dates are a declaration, not proof that the whole bank account reconciles.</p><ErrorNotice error={error}/><Action type="submit" disabled={!source||busy||loading}>Preview import</Action>{result&&<div role="status"><p>{result.rows.length} transactions · Money in {money(result.rows.filter(r=>r.amountPence>0).reduce((a,r)=>a+r.amountPence,0))} · Money out {money(-result.rows.filter(r=>r.amountPence<0).reduce((a,r)=>a+r.amountPence,0))}</p><p>{result.rows.filter(r=>r.possibleDuplicates.length||r.repeatedInFile).length} possible duplicates. {result.warning}</p>{result.alreadyImported?<p>This exact set of transactions is already imported.</p>:<Action disabled={busy||result.revision!==revision} onClick={async()=>{try{await save('stage',{...source,filename,coverageFrom:from,coverageThrough:through});setResult(null);setSource(null);}catch{/* outer error shown */}}}>Confirm import into review queue</Action>}</div>}</form>;
}
function OpeningForm({memberId,save,busy}) {
  const [amount,setAmount]=useState(''),[openingOn,setDate]=useState(''),[note,setNote]=useState(''),[confirmed,setConfirmed]=useState(false);
  const londonToday=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  const priorDay=new Date(`${londonToday}T00:00:00Z`);
  priorDay.setUTCDate(priorDay.getUTCDate()-1);
  const priorUKday=priorDay.toISOString().slice(0,10);
  return <form className="my-4 space-y-3" onSubmit={e=>{e.preventDefault();save('open',{memberId,amount,openingOn,note,confirmed}).catch(()=>{});}}><Field label="Approved opening balance (£; negative = debt)" value={amount} onChange={setAmount} required/><label className="block text-sm font-bold">Includes transactions and charges through<input className="manage-input" type="date" max={priorUKday} value={openingOn} onChange={e=>setDate(e.target.value)} required/></label><p>Choose a completed day before today in UK time (latest {priorUKday}). Use the verified balance through that date, including existing charges.</p><Field label="Evidence / reason (visible to member)" value={note} onChange={setNote} required/><label className="block"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I checked this opening balance and all charges included through this date. Credit will cover oldest due charges first.</label><Action type="submit" disabled={busy||!confirmed}>Approve and activate this account</Action></form>;
}
function RowForm({row,members,save,busy}) {
  const [status,setStatus]=useState('posted'),[note,setNote]=useState(''),[distinct,setDistinct]=useState(false),[splits,setSplits]=useState([{memberId:'',amount:String(Math.abs(row.amount_pence)/100),description:row.amount_pence>0?'Bank payment received':'Refund paid',eventCode:'',category:''}]);
  const change=(i,k,v)=>setSplits(old=>old.map((s,j)=>i===j?{...s,[k]:v}:s));
  return <form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();save('resolve',{id:row.id,status,note,distinctConfirmed:distinct,splits,reassign:row.status!=='pending'}).catch(()=>{});}}><Select label="Treatment" value={status} onChange={setStatus} options={[{value:'posted',label:row.amount_pence>0?'Credit member account(s)':'Confirmed refund to member(s)'},{value:'non_member',label:'Society expense / non-member movement / already in opening balance'},{value:'duplicate',label:'Already imported — duplicate'}]}/>
    {row.possibleDuplicate&&<label className="block"><input type="checkbox" checked={distinct} onChange={e=>setDistinct(e.target.checked)}/> I verified this is a separate bank movement, not the similar imported transaction.</label>}
    {status==='posted'&&<>{splits.map((s,i)=><div key={i} className="grid gap-3 border p-3 sm:grid-cols-2"><Select label="Member" value={s.memberId} onChange={v=>change(i,'memberId',v)} options={options(members)}/><Field label="Portion (£)" value={s.amount} onChange={v=>change(i,'amount',v)} required/><Field label="Event / trip code (e.g. RC26)" value={s.eventCode} onChange={v=>change(i,'eventCode',v)}/><Field label="Category (e.g. Accommodation)" value={s.category} onChange={v=>change(i,'category',v)}/><Field label="Member-visible description" value={s.description} onChange={v=>change(i,'description',v)} required/>{splits.length>1&&<Action onClick={()=>setSplits(old=>old.filter((_,j)=>i!==j))}>Remove portion</Action>}</div>)}<Action onClick={()=>setSplits(old=>[...old,{memberId:'',amount:'',description:'Bank payment received',eventCode:'',category:''}])}>Split across another member / category</Action></>}
    <Field label="Committee review note" value={note} onChange={setNote} required/><Action type="submit" disabled={busy}>Confirm treatment</Action></form>;
}
function EntryForm({account,save,busy}) {
  const [kind,setKind]=useState('charge'),[amount,setAmount]=useState(''),[postedOn,setDate]=useState(''),[dueOn,setDue]=useState(''),[eventCode,setEvent]=useState(''),[category,setCategory]=useState(''),[note,setNote]=useState(''),[requestId]=useState(()=>crypto.randomUUID());
  return <form className="my-4 grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();save('entry',{memberId:account.id,kind,amount,postedOn,dueOn,eventCode,category,note,requestId}).catch(()=>{});}}><Select label="Entry" value={kind} onChange={setKind} options={[{value:'charge',label:'Event / other charge'},{value:'credit',label:'Credit adjustment (not a bank receipt)'}]}/><Field label="Amount (£)" value={amount} onChange={setAmount} required/><Field label="Posting date" type="date" value={postedOn} onChange={setDate} required/><Field label="Due date" type="date" value={dueOn} onChange={setDue} required/><Field label="Event / trip code" value={eventCode} onChange={setEvent}/><Field label="Category" value={category} onChange={setCategory}/><Field label="Description and reason (member-visible)" value={note} onChange={setNote} required/><Action type="submit" disabled={busy}>Confirm entry</Action></form>;
}
function ReverseForm({id,save,busy,claim=false}) {
  const [note,setNote]=useState('');
  return <form className="my-2 flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();save(claim?'claim':'reverse',{id,note}).catch(()=>{});}}><Field label={claim?'Review outcome':'Reason for reversing this entry (member-visible)'} value={note} onChange={setNote} required/><Action type="submit" disabled={busy}>{claim?'Resolve claim':'Confirm reversal'}</Action></form>;
}
